version: '3.4'
services:
  config-server:
    image: dehemart/erp-config-server:latest
    container_name: erp-config-server
    ports:
      - 8888:8888
    environment:
      PORT: 8888
      PROPERTIES_URI: "https://github.com/dehemart/erp-properties"
      EUREKA_URI: "http://localhost:8761/eureka"