version: '3.4'
services:
  erp-config:
    image: dehemart/erp-config-server:latest
    container_name: erp-config
    ports:
      - 8888:8888
    environment:
      PORT: 8888
      PROPERTIES_URI: "https://github.com/dehemart/erp-properties"
