server:
  port: ${PORT:8888}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: ${PROPERTIES_URI:https://github.com/dehemart/erp-properties}
