server:
  port: ${PORT:8888}

spring:
  application:
    name: erp-configServer
  cloud:
    config:
      server:
        git:
          uri: ${PROPERTIES_URI:https://github.com/dehemart/erp-properties}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.17.0.1:8761/eureka}
  instance:
    preferIpAddress: true

