server:
  port: ${PORT:8888}

spring:
  application:
    name: erp-configServer
  cloud:
    config:
      server:
        git:
          uri: ${PROPERTIES_URI:https://github.com/dehemart/erp-properties}
